from colorama import *
def selections():
    print(Style.RESET_ALL)
    print(Fore.RED + "Bu termux app https://t.me/hurmatliy_bro\ntomonidan tayyorlandi")
    print("")
    command1 = (Fore.GREEN + "[1] Akkount qo'shish")
    command2 = (Fore.GREEN + "[2] Akkountlarni ko'rish")
    command3 = (Fore.GREEN + "[3] Kanallarga a'zo")
    command4 = (Fore.GREEN + "[4] Botga start bosish")
    command5 = (Fore.GREEN + "[5] So'rovnomga ovoz")
    command6 = (Fore.RED + "[6] Spam tekshirish")
    command7 = (Fore.RED + "[7] O'chib ketganarni tozalash")
    command8 = (Fore.RED + "[8] Akkountdan chiqish")
    command9 = (Fore.YELLOW + "[9] Premium yutganini tekshir")
    command0 = (Fore.RED + "[0] Chiqish")
    print(Style.RESET_ALL)
    print(f"{command1}\n{command2}\n{command3}\n{command4}\n{command5}\n{command6}\n{command7}\n{command8}\n{command9}\n\n{command0}\n{Style.RESET_ALL}")